"""user roles

Revision ID: 179ae2144b43
Revises: 17c2a561d0cc
Create Date: 2021-12-01 18:29:54.780877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179ae2144b43'
down_revision = '17c2a561d0cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account_type', sa.Enum('student', 'instructor', 'admin', name='accounttype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'account_type')
    # ### end Alembic commands ###
